export const SET_BOARDS = "SET_BOARDS";
export const NEW_BOARD = "NEW_BOARD";

export const OPEN_CREATE_BOARD = "OPEN_CREATE_BOARD";
export const CLOSE_CREATE_BOARD = "CLOSE_CREATE_BOARD";

export const SET_ACTIVE_BOARD = "SET_ACTIVE_BOARD";
export const ADD_ACTIVE_BOARD_TASKLISTS = "ADD_ACTIVE_BOARD_TASKLISTS";

export const OPEN_CREATE_TASK = "OPEN_CREATE_TASK";
export const CLOSE_CREATE_TASK = "CLOSE_CREATE_TASK";
